language: "en-US"
tone_instructions: "Please be professional, constructive, and focus on security, gas optimization, and best practices in Rust and smart contracts."
reviews:
  # Opt-in/out of PR reviews
  profile: "chill"  # Try 'chill', 'balanced', or 'assertive'
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true

early_access: false
